name: chifserver
services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=mongo
      - MONGO_INITDB_ROOT_USERNAME=mongo
    volumes:
      - $HOME/volumes/mongo:/data/db
    ports:
      - 27017:27017
  neo4j:
    image: neo4j:latest
    volumes:
      - $HOME/volumes/neo4j:/data
    ports:
      - 7687:7687
      - 7474:7474
